const header=document.getElementById("site-header"),menuButton=document.getElementById("menu-button"),mobileMenu=document.getElementById("mobile-menu");
const updateHeader=()=>header?.classList.toggle("is-scrolled",window.scrollY>24);window.addEventListener("scroll",updateHeader,{passive:true});updateHeader();
const closeMenu=()=>{menuButton?.classList.remove("is-open");menuButton?.setAttribute("aria-expanded","false");menuButton?.setAttribute("aria-label","Open menu");mobileMenu?.classList.add("hidden")};
menuButton?.addEventListener("click",()=>{const open=menuButton.classList.toggle("is-open");menuButton.setAttribute("aria-expanded",String(open));menuButton.setAttribute("aria-label",open?"Close menu":"Open menu");mobileMenu?.classList.toggle("hidden",!open)});
mobileMenu?.querySelectorAll("a").forEach(link=>link.addEventListener("click",closeMenu));
document.querySelectorAll("[data-reveal]").forEach(item=>{if(item.dataset.delay)item.style.setProperty("--reveal-delay",item.dataset.delay+"ms")});
const revealItems=document.querySelectorAll("[data-reveal]");
if("IntersectionObserver"in window){const observer=new IntersectionObserver((entries,obs)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");obs.unobserve(entry.target)}})},{threshold:.12,rootMargin:"0px 0px -35px"});revealItems.forEach(item=>observer.observe(item))}else revealItems.forEach(item=>item.classList.add("is-visible"));
const heroBook=document.querySelector(".book-stage"),reduceMotion=window.matchMedia("(prefers-reduced-motion: reduce)"),finePointer=window.matchMedia("(hover: hover) and (pointer: fine)");
if(heroBook&&finePointer.matches&&!reduceMotion.matches){let frame=null,targetX=0,targetY=0,currentX=0,currentY=0;const render=()=>{currentX+=(targetX-currentX)*.08;currentY+=(targetY-currentY)*.08;heroBook.style.setProperty("--book-tilt-x",currentY.toFixed(2)+"deg");heroBook.style.setProperty("--book-tilt-y",currentX.toFixed(2)+"deg");if(Math.abs(targetX-currentX)>.01||Math.abs(targetY-currentY)>.01)frame=requestAnimationFrame(render);else frame=null};heroBook.addEventListener("pointermove",e=>{const r=heroBook.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;targetX=Math.max(-2.2,Math.min(2.2,x*4.4));targetY=Math.max(-2.2,Math.min(2.2,-y*3.2));if(!frame)frame=requestAnimationFrame(render)});heroBook.addEventListener("pointerleave",()=>{targetX=targetY=0;if(!frame)frame=requestAnimationFrame(render)})}
window.addEventListener("resize",()=>{if(window.innerWidth>900)closeMenu()});
